### PR TITLE
Update Go module to reflect v2

### PR DESCRIPTION
**Pull request by thisisaaronland**
* Update module URI in `go.mod` to reflect v2 versioning
* Update to use `paulmach/orb` v0.8.0

Go versioning requires that v(N) releases be reflected in the URI specified in `go.mod`. For example release `v2.x.y` requires `protomaps/go-pmtiles/v2`.

### CODE REVIEW

**Comment by bdon** [comment]
Is this a hard requirement for you to use this as a library? I hadn't anticipated use as a library yet (#20 ) 

Also, can you squash your commits to be based off `main`?

**Comment by thisisaaronland** [comment]
It's a requirement for anyone wanting to use `go-pmtiles` as a library. Without the `v2` the Go vendoring stuff will always fetch Go 1.x

'Happy to squash the commits off of `main` just as soon as I figure out how to do that in Git :-)

**Comment by thisisaaronland** [comment]
I generally play faster and looser than most people when it comes to "semantic" versioning so, overall, I am easy about things.

That said, there are backwards incompatible changes in the 2.x releases, specifically changing `Loop` to `Server`, so it's not wrong to bump the module to `/v2`.

In an ideal world "v1" would always be the first "stable" release but that is rarely the case, right? If "stable" means bumping to `/v3` it won't be a big deal to me.

**Comment by bdon** [comment]
I attempted bumping go.mod via `module github.com/protomaps/go-pmtiles/v2` but then `go-tidy` brings in v1 (`module github.com/protomaps/go-pmtiles`) as a dependency in `go.mod`. 

for reference: https://donatstudios.com/Go-v2-Modules

**Comment by thisisaaronland** [comment]
You also need to reflect the "v2-iness" of things in the `import` statements in the code (like `main.go`).

**Comment by bdon** [comment]
I've made several attempts at this with no success - it looks like the only way to accomplish this is to duplicate my `go.mod` inside a `v2` top-level directory, then creating two semantically separate modules that I need to maintain. Strongly considering just going back to V1 until this project is "feature-complete" and I can consider a stable internal API, but that seems a long way off.

**Comment by bdon** [comment]
@thisisaaronland I just released 1.7.0 - is it possible to use that instead of v2?

**Comment by thisisaaronland** [comment]
It works, yes. Thanks.

**Comment by bdon** [comment]
I'm going to continue on the 1.X branch, then. I added a note to the Releases page for the 2.0 and 2.1 releases, pointing downloaders to 1.7.0. It doesn't look like I can or should delete the tags associated with v2.0.0 and v2.0.1. That might introduce problems related to Go modules, but there isn't a well defined API or use case for those yet. 

Going to close this issue for now, let me know if there's anything else that should be changed.

**Pull request closed without merging**
